# Generated by Django 2.0.6 on 2018-06-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('release_date', models.DateField(blank=True)),
                ('release_type', models.CharField(choices=[('SG', 'Single'), ('EP', 'Extended Play'), ('LP', 'Long Play')], default='LP', max_length=2)),
                ('desc', models.TextField(blank=True, max_length=2047)),
                ('img_path', models.URLField(blank=True, max_length=255)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('country', models.CharField(blank=True, max_length=31)),
                ('bio', models.TextField(blank=True, max_length=2047)),
                ('img_path', models.URLField(blank=True, max_length=255)),
                ('discog', models.ManyToManyField(to='music.Album')),
                ('members', models.ManyToManyField(related_name='bands', through='music.Membership', to='music.Artist')),
                ('related', models.ManyToManyField(related_name='_outline_related_+', to='music.Outline')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('disc_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('track_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='SongExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.URLField(blank=True, max_length=255)),
                ('lyrics', models.TextField(blank=True, max_length=8191)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base', to='music.SongExtend'),
        ),
        migrations.AddField(
            model_name='membership',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_memberships', to='music.Outline'),
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band_memberships', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='outline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base', to='music.Outline'),
        ),
        migrations.AddField(
            model_name='album',
            name='credits',
            field=models.ManyToManyField(blank=True, related_name='credited_on', to='music.Artist'),
        ),
    ]
